/**
 * Supported regions:
 * - ap-northeast-1 (version 119.1.0)
 * - ap-northeast-2 (version 119.1.0)
 * - ap-northeast-3 (version 119.1.0)
 * - ap-south-1 (version 119.1.0)
 * - ap-southeast-1 (version 119.1.0)
 * - ap-southeast-2 (version 119.1.0)
 * - ca-central-1 (version 119.1.0)
 * - eu-central-1 (version 119.1.0)
 * - eu-west-1 (version 119.1.0)
 * - eu-west-2 (version 119.1.0)
 * - eu-west-3 (version 119.1.0)
 * - sa-east-1 (version 119.1.0)
 * - us-east-1 (version 119.1.0)
 * - us-east-2 (version 119.1.0)
 * - us-west-1 (version 119.1.0)
 * - us-west-2 (version 119.1.0)
 */
import { List, Value } from '../../shared-types/dataTypes';
import { ResourceTag } from '../../shared-types/resource';

/**
 * `VpcConfig` is a property of the [AWS::CodeBuild::Project](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html) resource that enable AWS CodeBuild to access resources in an Amazon VPC. For more information, see [Use AWS CodeBuild with Amazon Virtual Private Cloud](https://docs.aws.amazon.com/codebuild/latest/userguide/vpc-support.html) in the _AWS CodeBuild User Guide_.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-vpcconfig.html}
 **/
export interface CodeBuildProjectVpcConfig {
  /**
   * A list of one or more subnet IDs in your Amazon VPC. The maximum count is 16.
   *
   * _Required_: No
   *
   * _Type_: List of String
   *
   * _Maximum_: `16`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Subnets?: List<Value<string>>;
  /**
   * The ID of the Amazon VPC.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Minimum_: `1`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  VpcId?: Value<string>;
  /**
   * A list of one or more security groups IDs in your Amazon VPC. The maximum count is 5.
   *
   * _Required_: No
   *
   * _Type_: List of String
   *
   * _Maximum_: `5`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  SecurityGroupIds?: List<Value<string>>;
}

/**
 * `Artifacts` is a property of the [ AWS::CodeBuild::Project](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html) resource that specifies output settings for artifacts generated by an AWS CodeBuild build.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-artifacts.html}
 **/
export interface CodeBuildProjectArtifacts {
  /**
   * Along with `namespaceType` and `name`, the pattern that AWS CodeBuild uses to name and store the output artifact:
   */
  Path?: Value<string>;
  /**
   * The type of build output artifact. Valid values include:
   */
  Type: Value<string>;
  /**
   * An identifier for this artifact definition.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  ArtifactIdentifier?: Value<string>;
  /**
   * If set to true a name specified in the buildspec file overrides the artifact name. The name specified in a buildspec file is calculated at build time and uses the Shell command language. For example, you can append a date and time to your artifact name so that it is always unique.
   *
   * _Required_: No
   *
   * _Type_: Boolean
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  OverrideArtifactName?: Value<boolean>;
  /**
   * The type of build output artifact to create:
   */
  Packaging?: Value<string>;
  /**
   * Set to true if you do not want your output artifacts encrypted. This option is valid only if your artifacts type is Amazon Simple Storage Service (Amazon S3). If this is set with another artifacts type, an `invalidInputException` is thrown.
   *
   * _Required_: No
   *
   * _Type_: Boolean
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  EncryptionDisabled?: Value<boolean>;
  /**
   * Information about the build output artifact location:
   */
  Location?: Value<string>;
  /**
   * Along with `path` and `namespaceType`, the pattern that AWS CodeBuild uses to name and store the output artifact:
   */
  Name?: Value<string>;
  /**
   * Along with `path` and `name`, the pattern that AWS CodeBuild uses to determine the name and location to store the output artifact:
   */
  NamespaceType?: Value<string>;
}

/**
 * `RegistryCredential` is a property of the [AWS CodeBuild Project Environment ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-environment.html) property type that specifies information about credentials that provide access to a private Docker registry. When this is set:
 *
 * For more information, see [Private Registry with AWS Secrets Manager Sample for AWS CodeBuild](https://docs.aws.amazon.com/codebuild/latest/userguide/sample-private-registry.html).
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-registrycredential.html}
 **/
export interface CodeBuildProjectRegistryCredential {
  /**
   * The Amazon Resource Name (ARN) or name of credentials created using AWS Secrets Manager.
   *
   * The `credential` can use the name of the credentials only if they exist in your current AWS Region.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Minimum_: `1`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Credential: Value<string>;
  /**
   * The service that created the credentials to access a private Docker registry. The valid value, SECRETS_MANAGER, is for AWS Secrets Manager.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Allowed values_: `SECRETS_MANAGER`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  CredentialProvider: Value<string>;
}

/**
 * Contains configuration information about a batch build project.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-projectbuildbatchconfig.html}
 **/
export interface CodeBuildProjectProjectBuildBatchConfig {
  /**
   * Specifies if the build artifacts for the batch build should be combined into a single artifact location.
   *
   * _Required_: No
   *
   * _Type_: Boolean
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  CombineArtifacts?: Value<boolean>;
  /**
   * Specifies the service role ARN for the batch build project.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Minimum_: `1`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  ServiceRole?: Value<string>;
  /**
   * Specifies how build status reports are sent to the source provider for the batch build. This property is only used when the source provider for your project is Bitbucket, GitHub, or GitHub Enterprise, and your project is configured to report build statuses to the source provider.
   *
   * REPORT_AGGREGATED_BATCH
   *
   * (Default) Aggregate all of the build statuses into a single status report.
   *
   * REPORT_INDIVIDUAL_BUILDS
   *
   * Send a separate status report for each individual build.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Allowed values_: `REPORT_AGGREGATED_BATCH | REPORT_INDIVIDUAL_BUILDS`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  BatchReportMode?: Value<string>;
  /**
   * Specifies the maximum amount of time, in minutes, that the batch build must be completed in.
   *
   * _Required_: No
   *
   * _Type_: Integer
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  TimeoutInMins?: Value<number>;
  /**
   * A `BatchRestrictions` object that specifies the restrictions for the batch build.
   *
   * _Required_: No
   *
   * _Type_: [BatchRestrictions](aws-properties-codebuild-project-batchrestrictions.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Restrictions?: CodeBuildProjectBatchRestrictions;
}

/**
 * Specifies restrictions for the batch build.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-batchrestrictions.html}
 **/
export interface CodeBuildProjectBatchRestrictions {
  /**
   * An array of strings that specify the compute types that are allowed for the batch build. See [Build environment compute types](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-compute-types.html) in the _ AWS CodeBuild User Guide_ for these values.
   *
   * _Required_: No
   *
   * _Type_: List of String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  ComputeTypesAllowed?: List<Value<string>>;
  /**
   * Specifies the maximum number of builds allowed.
   *
   * _Required_: No
   *
   * _Type_: Integer
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  MaximumBuildsAllowed?: Value<number>;
}

/**
 * `Source` is a property of the [AWS::CodeBuild::Project](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html) resource that specifies the source code settings for the project, such as the source code's repository type and location.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-source.html}
 **/
export interface CodeBuildProjectSource {
  /**
   * The type of repository that contains the source code to be built. Valid values include:
   */
  Type: Value<string>;
  /**
   * Set to true to report the status of a build's start and finish to your source provider. This option is valid only when your source provider is GitHub, GitHub Enterprise, or Bitbucket. If this is set and you use a different source provider, an `invalidInputException` is thrown.
   *
   * _Required_: No
   *
   * _Type_: Boolean
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  ReportBuildStatus?: Value<boolean>;
  /**
   * Information about the authorization settings for AWS CodeBuild to access the source code to be built.
   *
   * This information is for the AWS CodeBuild console's use only. Your code should not get or set `Auth` directly.
   *
   * _Required_: No
   *
   * _Type_: [SourceAuth](aws-properties-codebuild-project-sourceauth.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Auth?: CodeBuildProjectSourceAuth;
  /**
   * An identifier for this project source. The identifier can only contain alphanumeric characters and underscores, and must be less than 128 characters in length.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  SourceIdentifier?: Value<string>;
  /**
   * The build specification for the project. If this value is not provided, then the source code must contain a buildspec file named `buildspec.yml` at the root level. If this value is provided, it can be either a single string containing the entire build specification, or the path to an alternate buildspec file relative to the value of the built-in environment variable `CODEBUILD_SRC_DIR`. The alternate buildspec file can have a name other than `buildspec.yml`, for example `myspec.yml` or `build_spec_qa.yml` or similar. For more information, see the [Build Spec Reference](https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-example) in the _AWS CodeBuild User Guide_.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  BuildSpec?: Value<string>;
  /**
   * The depth of history to download. Minimum value is 0. If this value is 0, greater than 25, or not provided, then the full history is downloaded with each build project. If your source type is Amazon S3, this value is not supported.
   *
   * _Required_: No
   *
   * _Type_: Integer
   *
   * _Minimum_: `0`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  GitCloneDepth?: Value<number>;
  /**
   * Contains information that defines how the build project reports the build status to the source provider. This option is only used when the source provider is `GITHUB`, `GITHUB_ENTERPRISE`, or `BITBUCKET`.
   *
   * _Required_: No
   *
   * _Type_: [BuildStatusConfig](aws-properties-codebuild-project-buildstatusconfig.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  BuildStatusConfig?: CodeBuildProjectBuildStatusConfig;
  /**
   * Information about the Git submodules configuration for the build project.
   *
   * _Required_: No
   *
   * _Type_: [GitSubmodulesConfig](aws-properties-codebuild-project-gitsubmodulesconfig.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  GitSubmodulesConfig?: CodeBuildProjectGitSubmodulesConfig;
  /**
   * This is used with GitHub Enterprise only. Set to true to ignore SSL warnings while connecting to your GitHub Enterprise project repository. The default value is `false`. `InsecureSsl` should be used for testing purposes only. It should not be used in a production environment.
   *
   * _Required_: No
   *
   * _Type_: Boolean
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  InsecureSsl?: Value<boolean>;
  /**
   * Information about the location of the source code to be built. Valid values include:
   */
  Location?: Value<string>;
}

/**
 * A source identifier and its corresponding version.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-projectsourceversion.html}
 **/
export interface CodeBuildProjectProjectSourceVersion {
  /**
   * An identifier for a source in the build project. The identifier can only contain alphanumeric characters and underscores, and must be less than 128 characters in length.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  SourceIdentifier: Value<string>;
  /**
   * The source version for the corresponding source identifier. If specified, must be one of:
   */
  SourceVersion?: Value<string>;
}

/**
 * `S3Logs` is a property of the [AWS CodeBuild Project LogsConfig ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-logsconfig.html) property type that specifies settings for logs generated by an AWS CodeBuild build in an S3 bucket.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-s3logsconfig.html}
 **/
export interface CodeBuildProjectS3LogsConfig {
  /**
   * The current status of the S3 build logs. Valid values are:
   */
  Status: Value<string>;
  /**
   * Set to true if you do not want your S3 build log output encrypted. By default S3 build logs are encrypted.
   *
   * _Required_: No
   *
   * _Type_: Boolean
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  EncryptionDisabled?: Value<boolean>;
  /**
   * The ARN of an S3 bucket and the path prefix for S3 logs. If your Amazon S3 bucket name is `my-bucket`, and your path prefix is `build-log`, then acceptable formats are `my-bucket/build-log` or `arn:aws:s3:::my-bucket/build-log`.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Location?: Value<string>;
}

/**
 * `Environment` is a property of the [AWS::CodeBuild::Project](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html) resource that specifies the environment for an AWS CodeBuild project.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-environment.html}
 **/
export interface CodeBuildProjectEnvironment {
  /**
   * The type of build environment to use for related builds.
   */
  Type: Value<string>;
  /**
   * A set of environment variables to make available to builds for this build project.
   *
   * _Required_: No
   *
   * _Type_: List of [EnvironmentVariable](aws-properties-codebuild-project-environmentvariable.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  EnvironmentVariables?: List<CodeBuildProjectEnvironmentVariable>;
  /**
   * Enables running the Docker daemon inside a Docker container. Set to true only if the build project is used to build Docker images. Otherwise, a build that attempts to interact with the Docker daemon fails. The default setting is `false`.
   *
   * You can initialize the Docker daemon during the install phase of your build by adding one of the following sets of commands to the install phase of your buildspec file:
   *
   * If the operating system's base image is Ubuntu Linux:
   *
   * `- nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&`
   *
   * `- timeout 15 sh -c "until docker info; do echo .; sleep 1; done"`
   *
   * If the operating system's base image is Alpine Linux and the previous command does not work, add the `-t` argument to `timeout`:
   *
   * `- nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&`
   *
   * `- timeout -t 15 sh -c "until docker info; do echo .; sleep 1; done"`
   *
   * _Required_: No
   *
   * _Type_: Boolean
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  PrivilegedMode?: Value<boolean>;
  /**
   * The type of credentials AWS CodeBuild uses to pull images in your build. There are two valid values:
   */
  ImagePullCredentialsType?: Value<string>;
  /**
   * The image tag or image digest that identifies the Docker image to use for this build project. Use the following formats:
   */
  Image: Value<string>;
  /**
   * `RegistryCredential` is a property of the [AWS::CodeBuild::Project Environment ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html#cfn-codebuild-project-environment) property that specifies information about credentials that provide access to a private Docker registry. When this is set:
   */
  RegistryCredential?: CodeBuildProjectRegistryCredential;
  /**
   * The type of compute environment. This determines the number of CPU cores and memory the build environment uses. Available values include:
   */
  ComputeType: Value<string>;
  /**
   * The ARN of the Amazon S3 bucket, path prefix, and object key that contains the PEM-encoded certificate for the build project. For more information, see [certificate](https://docs.aws.amazon.com/codebuild/latest/userguide/create-project-cli.html#cli.environment.certificate) in the _ AWS CodeBuild User Guide_.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Certificate?: Value<string>;
}

/**
 * `GitSubmodulesConfig` is a property of the [AWS CodeBuild Project Source](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-source.html) property type that specifies information about the Git submodules configuration for the build project.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-gitsubmodulesconfig.html}
 **/
export interface CodeBuildProjectGitSubmodulesConfig {
  /**
   * Set to true to fetch Git submodules for your AWS CodeBuild build project.
   *
   * _Required_: Yes
   *
   * _Type_: Boolean
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  FetchSubmodules: Value<boolean>;
}

/**
 * `CloudWatchLogs` is a property of the [AWS CodeBuild Project LogsConfig ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-logsconfig.html) property type that specifies settings for CloudWatch logs generated by an AWS CodeBuild build.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-cloudwatchlogsconfig.html}
 **/
export interface CodeBuildProjectCloudWatchLogsConfig {
  /**
   * The current status of the logs in CloudWatch Logs for a build project. Valid values are:
   */
  Status: Value<string>;
  /**
   * The group name of the logs in CloudWatch Logs. For more information, see [Working with Log Groups and Log Streams](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Working-with-log-groups-and-streams.html).
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  GroupName?: Value<string>;
  /**
   * The prefix of the stream name of the CloudWatch Logs. For more information, see [Working with Log Groups and Log Streams](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Working-with-log-groups-and-streams.html).
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  StreamName?: Value<string>;
}

/**
 * `ProjectCache` is a property of the [AWS CodeBuild Project](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html) resource that specifies information about the cache for the build project. If `ProjectCache` is not specified, then both of its properties default to `NO_CACHE`.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-projectcache.html}
 **/
export interface CodeBuildProjectProjectCache {
  /**
   * An array of strings that specify the local cache modes. You can use one or more local cache modes at the same time. This is only used for `LOCAL` cache types.
   *
   * Possible values are:
   *
   * LOCAL_SOURCE_CACHE
   *
   * Caches Git metadata for primary and secondary sources. After the cache is created, subsequent builds pull only the change between commits. This mode is a good choice for projects with a clean working directory and a source that is a large Git repository. If you choose this option and your project does not use a Git repository (GitHub, GitHub Enterprise, or Bitbucket), the option is ignored.
   *
   * LOCAL_DOCKER_LAYER_CACHE
   *
   * Caches existing Docker layers. This mode is a good choice for projects that build or pull large Docker images. It can prevent the performance issues caused by pulling large Docker images down from the network.
   */
  Modes?: List<Value<string>>;
  /**
   * The type of cache used by the build project. Valid values include:
   */
  Type: Value<string>;
  /**
   * Information about the cache location:
   */
  Location?: Value<string>;
}

/**
 * A list of `WebhookFilter` objects used to determine which webhook events are triggered. At least one `WebhookFilter` in the list must specify `EVENT` as its type. The `FilterGroups` property of the [AWS CodeBuild Project ProjectTriggers](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-projecttriggers.html) property type is a list of `FilterGroup` objects.
 *
 * _Required:_ No
 *
 * _Type:_ A list of [WebhookFilter](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-webhookfilter.html) objects
 *
 * _Update requires:_ No interruption
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-filtergroup.html}
 **/
export type CodeBuildProjectFilterGroup = List<CodeBuildProjectWebhookFilter>;

/**
 * `ProjectTriggers` is a property of the [AWS CodeBuild Project](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html) resource that specifies webhooks that trigger an AWS CodeBuild build.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-projecttriggers.html}
 **/
export interface CodeBuildProjectProjectTriggers {
  /**
   * A list of lists of `WebhookFilter` objects used to determine which webhook events are triggered. At least one `WebhookFilter` in the array must specify `EVENT` as its type.
   *
   * _Required_: No
   *
   * _Type_: List of [FilterGroup](aws-properties-codebuild-project-filtergroup.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  FilterGroups?: List<CodeBuildProjectFilterGroup>;
  /**
   * Specifies the type of build this webhook will trigger. Allowed values are:
   *
   * BUILD
   *
   * A single build
   *
   * BUILD_BATCH
   *
   * A batch build
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  BuildType?: Value<string>;
  /**
   * Specifies whether or not to begin automatically rebuilding the source code every time a code change is pushed to the repository.
   *
   * _Required_: No
   *
   * _Type_: Boolean
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Webhook?: Value<boolean>;
}

/**
 * `LogsConfig` is a property of the [AWS CodeBuild Project](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html) resource that specifies information about logs for a build project. These can be logs in Amazon CloudWatch Logs, built in a specified S3 bucket, or both.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-logsconfig.html}
 **/
export interface CodeBuildProjectLogsConfig {
  /**
   * Information about CloudWatch Logs for a build project. CloudWatch Logs are enabled by default.
   *
   * _Required_: No
   *
   * _Type_: [CloudWatchLogsConfig](aws-properties-codebuild-project-cloudwatchlogsconfig.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  CloudWatchLogs?: CodeBuildProjectCloudWatchLogsConfig;
  /**
   * Information about logs built to an S3 bucket for a build project. S3 logs are not enabled by default.
   *
   * _Required_: No
   *
   * _Type_: [S3LogsConfig](aws-properties-codebuild-project-s3logsconfig.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  S3Logs?: CodeBuildProjectS3LogsConfig;
}

/**
 * `SourceAuth` is a property of the [AWS CodeBuild Project Source ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-source.html) property type that specifies authorization settings for AWS CodeBuild to access the source code to be built.
 *
 * `SourceAuth` is for use by the CodeBuild console only. Do not get or set it directly.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-sourceauth.html}
 **/
export interface CodeBuildProjectSourceAuth {
  /**
   * The authorization type to use. The only valid value is `OAUTH`, which represents the OAuth authorization type.
   *
   * This data type is used by the AWS CodeBuild console only.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Allowed values_: `OAUTH`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Type: Value<string>;
  /**
   * The resource value that applies to the specified authorization type.
   *
   * This data type is used by the AWS CodeBuild console only.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Resource?: Value<string>;
}

/**
 * Information about a file system created by Amazon Elastic File System (EFS). For more information, see [What Is Amazon Elastic File System?](https://docs.aws.amazon.com/efs/latest/ug/whatisefs.html)
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-projectfilesystemlocation.html}
 **/
export interface CodeBuildProjectProjectFileSystemLocation {
  /**
   * The location in the container where you mount the file system.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  MountPoint: Value<string>;
  /**
   * The type of the file system. The one supported type is `EFS`.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Allowed values_: `EFS`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Type: Value<string>;
  /**
   * The name used to access a file system created by Amazon EFS. CodeBuild creates an environment variable by appending the `identifier` in all capital letters to `CODEBUILD_`. For example, if you specify `my_efs` for `identifier`, a new environment variable is create named `CODEBUILD_MY_EFS`.
   *
   * The `identifier` is used to mount your file system.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Identifier: Value<string>;
  /**
   * The mount options for a file system created by Amazon EFS. The default mount options used by CodeBuild are `nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2`. For more information, see [Recommended NFS Mount Options](https://docs.aws.amazon.com/efs/latest/ug/mounting-fs-nfs-mount-settings.html).
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  MountOptions?: Value<string>;
  /**
   * A string that specifies the location of the file system created by Amazon EFS. Its format is `efs-dns-name:/directory-path`. You can find the DNS name of file system when you view it in the Amazon EFS console. The directory path is a path to a directory in the file system that CodeBuild mounts. For example, if the DNS name of a file system is `fs-abcd1234.efs.us-west-2.amazonaws.com`, and its mount directory is `my-efs-mount-directory`, then the `location` is `fs-abcd1234.efs.us-west-2.amazonaws.com:/my-efs-mount-directory`.
   *
   * The directory path in the format `efs-dns-name:/directory-path` is optional. If you do not specify a directory path, the location is only the DNS name and CodeBuild mounts the entire file system.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Location: Value<string>;
}

/**
 * `WebhookFilter` is a structure of the `FilterGroups` property on the [AWS CodeBuild Project ProjectTriggers](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-projecttriggers.html) property type that specifies which webhooks trigger an AWS CodeBuild build.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-webhookfilter.html}
 **/
export interface CodeBuildProjectWebhookFilter {
  /**
   * For a `WebHookFilter` that uses `EVENT` type, a comma-separated string that specifies one or more events. For example, the webhook filter `PUSH, PULL_REQUEST_CREATED, PULL_REQUEST_UPDATED` allows all push, pull request created, and pull request updated events to trigger a build.
   *
   * For a `WebHookFilter` that uses any of the other filter types, a regular expression pattern. For example, a `WebHookFilter` that uses `HEAD_REF` for its `type` and the pattern `^refs/heads/` triggers a build when the head reference is a branch with a reference name `refs/heads/branch-name`.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Pattern: Value<string>;
  /**
   * The type of webhook filter. There are six webhook filter types: `EVENT`, `ACTOR_ACCOUNT_ID`, `HEAD_REF`, `BASE_REF`, `FILE_PATH`, and `COMMIT_MESSAGE`.
   *
   * EVENT
   *
   * A webhook event triggers a build when the provided `pattern` matches one of five event types: `PUSH`, `PULL_REQUEST_CREATED`, `PULL_REQUEST_UPDATED`, `PULL_REQUEST_REOPENED`, and `PULL_REQUEST_MERGED`. The `EVENT` patterns are specified as a comma-separated string. For example, `PUSH, PULL_REQUEST_CREATED, PULL_REQUEST_UPDATED` filters all push, pull request created, and pull request updated events.
   *
   * The `PULL_REQUEST_REOPENED` works with GitHub and GitHub Enterprise only.
   *
   * ACTOR_ACCOUNT_ID
   *
   * A webhook event triggers a build when a GitHub, GitHub Enterprise, or Bitbucket account ID matches the regular expression `pattern`.
   *
   * HEAD_REF
   *
   * A webhook event triggers a build when the head reference matches the regular expression `pattern`. For example, `refs/heads/branch-name` and `refs/tags/tag-name`.
   *
   * Works with GitHub and GitHub Enterprise push, GitHub and GitHub Enterprise pull request, Bitbucket push, and Bitbucket pull request events.
   *
   * BASE_REF
   *
   * A webhook event triggers a build when the base reference matches the regular expression `pattern`. For example, `refs/heads/branch-name`.
   *
   * Works with pull request events only.
   *
   * FILE_PATH
   *
   * A webhook triggers a build when the path of a changed file matches the regular expression `pattern`.
   *
   * Works with GitHub and Bitbucket events push and pull requests events. Also works with GitHub Enterprise push events, but does not work with GitHub Enterprise pull request events.
   *
   * COMMIT_MESSAGE
   *
   * A webhook triggers a build when the head commit message matches the regular expression `pattern`.
   *
   * Works with GitHub and Bitbucket events push and pull requests events. Also works with GitHub Enterprise push events, but does not work with GitHub Enterprise pull request events.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Allowed values_: `ACTOR_ACCOUNT_ID | BASE_REF | COMMIT_MESSAGE | EVENT | FILE_PATH | HEAD_REF`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Type: Value<string>;
  /**
   * Used to indicate that the `pattern` determines which webhook events do not trigger a build. If true, then a webhook event that does not match the `pattern` triggers a build. If false, then a webhook event that matches the `pattern` triggers a build.
   *
   * _Required_: No
   *
   * _Type_: Boolean
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  ExcludeMatchedPattern?: Value<boolean>;
}

/**
 * Contains information that defines how the AWS CodeBuild build project reports the build status to the source provider.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-buildstatusconfig.html}
 **/
export interface CodeBuildProjectBuildStatusConfig {
  /**
   * Specifies the context of the build status CodeBuild sends to the source provider. The usage of this parameter depends on the source provider.
   *
   * Bitbucket
   *
   * This parameter is used for the `name` parameter in the Bitbucket commit status. For more information, see [build](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/commit/%7Bnode%7D/statuses/build) in the Bitbucket API documentation.
   *
   * GitHub/GitHub Enterprise Server
   *
   * This parameter is used for the `context` parameter in the GitHub commit status. For more information, see [Create a commit status](https://developer.github.com/v3/repos/statuses/#create-a-commit-status) in the GitHub developer guide.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Context?: Value<string>;
  /**
   * Specifies the target url of the build status CodeBuild sends to the source provider. The usage of this parameter depends on the source provider.
   *
   * Bitbucket
   *
   * This parameter is used for the `url` parameter in the Bitbucket commit status. For more information, see [build](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/commit/%7Bnode%7D/statuses/build) in the Bitbucket API documentation.
   *
   * GitHub/GitHub Enterprise Server
   *
   * This parameter is used for the `target_url` parameter in the GitHub commit status. For more information, see [Create a commit status](https://developer.github.com/v3/repos/statuses/#create-a-commit-status) in the GitHub developer guide.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  TargetUrl?: Value<string>;
}

/**
 * `EnvironmentVariable` is a property of the [AWS CodeBuild Project Environment](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-environment.html) property type that specifies the name and value of an environment variable for an AWS CodeBuild project environment. When you use the environment to run a build, these variables are available for your builds to use. `EnvironmentVariable` contains a list of `EnvironmentVariable` property types.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-environmentvariable.html}
 **/
export interface CodeBuildProjectEnvironmentVariable {
  /**
   * The type of environment variable. Valid values include:
   */
  Type?: Value<string>;
  /**
   * The value of the environment variable.
   *
   * We strongly discourage the use of `PLAINTEXT` environment variables to store sensitive values, especially AWS secret key IDs and secret access keys. `PLAINTEXT` environment variables can be displayed in plain text using the AWS CodeBuild console and the AWS CLI. For sensitive values, we recommend you use an environment variable of type `PARAMETER_STORE` or `SECRETS_MANAGER`.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Value: Value<string>;
  /**
   * The name or key of the environment variable.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Minimum_: `1`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Name: Value<string>;
}
export interface CodeBuildProjectProperties {
  /**
   * A description that makes the build project easy to identify.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Minimum_: `0`
   *
   * _Maximum_: `255`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Description?: Value<string>;
  /**
   * The ARN of the IAM role that enables CodeBuild to access the CloudWatch Logs and Amazon S3 artifacts for the project's builds.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Minimum_: `1`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  ResourceAccessRole?: Value<string>;
  /**
   * `VpcConfig` specifies settings that enable AWS CodeBuild to access resources in an Amazon VPC. For more information, see [Use AWS CodeBuild with Amazon Virtual Private Cloud](https://docs.aws.amazon.com/codebuild/latest/userguide/vpc-support.html) in the _AWS CodeBuild User Guide_.
   *
   * _Required_: No
   *
   * _Type_: [VpcConfig](aws-properties-codebuild-project-vpcconfig.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  VpcConfig?: CodeBuildProjectVpcConfig;
  /**
   * An array of `ProjectSource` objects.
   *
   * _Required_: No
   *
   * _Type_: List of [Source](aws-properties-codebuild-project-source.md)
   *
   * _Maximum_: `12`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  SecondarySources?: List<CodeBuildProjectSource>;
  /**
   * The AWS Key Management Service customer master key (CMK) to be used for encrypting the build output artifacts.
   *
   * You can use a cross-account KMS key to encrypt the build output artifacts if your service role has permission to that key.
   *
   * You can specify either the Amazon Resource Name (ARN) of the CMK or, if available, the CMK's alias (using the format `alias/<alias-name>`). If you don't specify a value, CodeBuild uses the managed CMK for Amazon Simple Storage Service (Amazon S3).
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Minimum_: `1`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  EncryptionKey?: Value<string>;
  /**
   * A version of the build input to be built for this project. If not specified, the latest version is used. If specified, it must be one of:
   */
  SourceVersion?: Value<string>;
  /**
   * For an existing AWS CodeBuild build project that has its source code stored in a GitHub repository, enables AWS CodeBuild to begin automatically rebuilding the source code every time a code change is pushed to the repository.
   *
   * _Required_: No
   *
   * _Type_: [ProjectTriggers](aws-properties-codebuild-project-projecttriggers.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Triggers?: CodeBuildProjectProjectTriggers;
  /**
   * A list of `Artifacts` objects. Each artifacts object specifies output settings that the project generates during a build.
   *
   * _Required_: No
   *
   * _Type_: List of [Artifacts](aws-properties-codebuild-project-artifacts.md)
   *
   * _Maximum_: `12`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  SecondaryArtifacts?: List<CodeBuildProjectArtifacts>;
  /**
   * The source code settings for the project, such as the source code's repository type and location.
   *
   * _Required_: Yes
   *
   * _Type_: [Source](aws-properties-codebuild-project-source.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Source: CodeBuildProjectSource;
  /**
   * The name of the build project. The name must be unique across all of the projects in your AWS account.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Minimum_: `2`
   *
   * _Maximum_: `255`
   *
   * _Pattern_: `[A-Za-z0-9][A-Za-z0-9-_]{1,254}`
   *
   * _Update requires_: [Replacement](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-replacement)
   */
  Name?: Value<string>;
  /**
   * `Artifacts` is a property of the [ AWS::CodeBuild::Project](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html) resource that specifies output settings for artifacts generated by an AWS CodeBuild build.
   *
   * _Required_: Yes
   *
   * _Type_: [Artifacts](aws-properties-codebuild-project-artifacts.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Artifacts: CodeBuildProjectArtifacts;
  /**
   * Indicates whether AWS CodeBuild generates a publicly accessible URL for your project's build badge. For more information, see [Build Badges Sample](https://docs.aws.amazon.com/codebuild/latest/userguide/sample-build-badges.html) in the _AWS CodeBuild User Guide_.
   *
   * Including build badges with your project is currently not supported if the source type is CodePipeline. If you specify `CODEPIPELINE` for the `Source` property, do not specify the `BadgeEnabled` property.
   *
   * _Required_: No
   *
   * _Type_: Boolean
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  BadgeEnabled?: Value<boolean>;
  /**
   * Information about logs for the build project. A project can create logs in CloudWatch Logs, an S3 bucket, or both.
   *
   * _Required_: No
   *
   * _Type_: [LogsConfig](aws-properties-codebuild-project-logsconfig.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  LogsConfig?: CodeBuildProjectLogsConfig;
  /**
   * The ARN of the IAM role that enables AWS CodeBuild to interact with dependent AWS services on behalf of the AWS account.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Minimum_: `1`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  ServiceRole: Value<string>;
  /**
   * The number of minutes a build is allowed to be queued before it times out.
   *
   * _Required_: No
   *
   * _Type_: Integer
   *
   * _Minimum_: `5`
   *
   * _Maximum_: `480`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  QueuedTimeoutInMinutes?: Value<number>;
  /**
   * An array of `ProjectFileSystemLocation` objects for a CodeBuild build project. A `ProjectFileSystemLocation` object specifies the `identifier`, `location`, `mountOptions`, `mountPoint`, and `type` of a file system created using Amazon Elastic File System.
   *
   * _Required_: No
   *
   * _Type_: List of [ProjectFileSystemLocation](aws-properties-codebuild-project-projectfilesystemlocation.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  FileSystemLocations?: List<CodeBuildProjectProjectFileSystemLocation>;
  /**
   * The build environment settings for the project, such as the environment type or the environment variables to use for the build environment.
   *
   * _Required_: Yes
   *
   * _Type_: [Environment](aws-properties-codebuild-project-environment.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Environment: CodeBuildProjectEnvironment;
  /**
   * An array of `ProjectSourceVersion` objects. If `secondarySourceVersions` is specified at the build level, then they take over these `secondarySourceVersions` (at the project level).
   *
   * _Required_: No
   *
   * _Type_: List of [ProjectSourceVersion](aws-properties-codebuild-project-projectsourceversion.md)
   *
   * _Maximum_: `12`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  SecondarySourceVersions?: List<CodeBuildProjectProjectSourceVersion>;
  /**
   * The maximum number of concurrent builds that are allowed for this project.
   *
   * New builds are only started if the current number of builds is less than or equal to this limit. If the current build count meets this limit, new builds are throttled and are not run.
   *
   * _Required_: No
   *
   * _Type_: Integer
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  ConcurrentBuildLimit?: Value<number>;
  /**
   * Specifies the visibility of the project's builds. Possible values are:
   *
   * PUBLIC_READ
   *
   * The project builds are visible to the public.
   *
   * PRIVATE
   *
   * The project builds are not visible to the public.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Visibility?: Value<string>;
  /**
   * A `ProjectBuildBatchConfig` object that defines the batch build options for the project.
   *
   * _Required_: No
   *
   * _Type_: [ProjectBuildBatchConfig](aws-properties-codebuild-project-projectbuildbatchconfig.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  BuildBatchConfig?: CodeBuildProjectProjectBuildBatchConfig;
  /**
   * An arbitrary set of tags (key-value pairs) for the AWS CodeBuild project.
   *
   * These tags are available for use by AWS services that support AWS CodeBuild build project tags.
   *
   * _Required_: No
   *
   * _Type_: List of [Tag](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html)
   *
   * _Maximum_: `50`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Tags?: List<ResourceTag>;
  /**
   * How long, in minutes, from 5 to 480 (8 hours), for AWS CodeBuild to wait before timing out any related build that did not get marked as completed. The default is 60 minutes.
   *
   * _Required_: No
   *
   * _Type_: Integer
   *
   * _Minimum_: `5`
   *
   * _Maximum_: `480`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  TimeoutInMinutes?: Value<number>;
  /**
   * Settings that AWS CodeBuild uses to store and reuse build dependencies.
   *
   * _Required_: No
   *
   * _Type_: [ProjectCache](aws-properties-codebuild-project-projectcache.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Cache?: CodeBuildProjectProjectCache;
}

/**
 * The `AWS::CodeBuild::Project` resource configures how AWS CodeBuild builds your source code. For example, it tells CodeBuild where to get the source code and which build environment to use.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html}
 */
export interface CodeBuildProjectResource {
  Type: 'AWS::CodeBuild::Project';
  Properties: CodeBuildProjectProperties;
}
