/**
 * Supported regions:
 * - ap-northeast-1 (version 119.1.0)
 * - ap-northeast-2 (version 119.1.0)
 * - ap-south-1 (version 119.1.0)
 * - ap-southeast-1 (version 119.1.0)
 * - ap-southeast-2 (version 119.1.0)
 * - ca-central-1 (version 119.1.0)
 * - eu-central-1 (version 119.1.0)
 * - eu-west-1 (version 119.1.0)
 * - eu-west-2 (version 119.1.0)
 * - eu-west-3 (version 119.1.0)
 * - sa-east-1 (version 119.1.0)
 * - us-east-1 (version 119.1.0)
 * - us-east-2 (version 119.1.0)
 * - us-west-1 (version 119.1.0)
 * - us-west-2 (version 119.1.0)
 */
import { List, Value } from '../../shared-types/dataTypes';
import { ResourceTag } from '../../shared-types/resource';

/**
 * Configuration for data quality validation. Used to select the Rulesets and Validation Mode to be used in the profile job. When ValidationConfiguration is null, the profile job will run without data quality validation.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-job-validationconfiguration.html}
 **/
export interface DataBrewJobValidationConfiguration {
  /**
   * The Amazon Resource Name (ARN) for the ruleset to be validated in the profile job. The TargetArn of the selected ruleset should be the same as the Amazon Resource Name (ARN) of the dataset that is associated with the profile job.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  RulesetArn: Value<string>;
  /**
   * Mode of data quality validation. Default mode is “CHECK_ALL” which verifies all rules defined in the selected ruleset.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  ValidationMode?: Value<string>;
}

/**
 * Represents options that specify how and where in the AWS Glue Data Catalog DataBrew writes the output generated by recipe jobs.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-job-datacatalogoutput.html}
 **/
export interface DataBrewJobDataCatalogOutput {
  /**
   * The name of a table in the Data Catalog.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Minimum_: `1`
   *
   * _Maximum_: `255`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  TableName: Value<string>;
  /**
   * A value that, if true, means that any data in the location specified for output is overwritten with new output. Not supported with DatabaseOptions.
   *
   * _Required_: No
   *
   * _Type_: Boolean
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Overwrite?: Value<boolean>;
  /**
   * Represents options that specify how and where DataBrew writes the Amazon S3 output generated by recipe jobs.
   *
   * _Required_: No
   *
   * _Type_: [S3TableOutputOptions](aws-properties-databrew-job-s3tableoutputoptions.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  S3Options?: DataBrewJobS3TableOutputOptions;
  /**
   * Represents options that specify how and where DataBrew writes the database output generated by recipe jobs.
   *
   * _Required_: No
   *
   * _Type_: [DatabaseTableOutputOptions](aws-properties-databrew-job-databasetableoutputoptions.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  DatabaseOptions?: DataBrewJobDatabaseTableOutputOptions;
  /**
   * The name of a database in the Data Catalog.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Minimum_: `1`
   *
   * _Maximum_: `255`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  DatabaseName: Value<string>;
  /**
   * The unique identifier of the AWS account that holds the Data Catalog that stores the data.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Minimum_: `1`
   *
   * _Maximum_: `255`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  CatalogId?: Value<string>;
}

/**
 * Represents an Amazon S3 location (bucket name, bucket owner, and object key) where DataBrew can read input data, or write output from a job.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-job-s3location.html}
 **/
export interface DataBrewJobS3Location {
  /**
   * The Amazon S3 bucket name.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Minimum_: `3`
   *
   * _Maximum_: `63`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Bucket: Value<string>;
  /**
   * The AWS account ID of the bucket owner.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Minimum_: `12`
   *
   * _Maximum_: `12`
   *
   * _Pattern_: `^[0-9]{12}$`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  BucketOwner?: Value<string>;
  /**
   * The unique name of the object in the bucket.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Minimum_: `1`
   *
   * _Maximum_: `1280`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Key?: Value<string>;
}

/**
 * Represents a set of options that define the structure of comma-separated (CSV) job output.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-job-outputformatoptions.html}
 **/
export interface DataBrewJobOutputFormatOptions {
  /**
   * Represents a set of options that define the structure of comma-separated value (CSV) job output.
   *
   * _Required_: No
   *
   * _Type_: [CsvOutputOptions](aws-properties-databrew-job-csvoutputoptions.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Csv?: DataBrewJobCsvOutputOptions;
}

/**
 * Represents options that specify how and where DataBrew writes the Amazon S3 output generated by recipe jobs.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-job-s3tableoutputoptions.html}
 **/
export interface DataBrewJobS3TableOutputOptions {
  /**
   * Represents an Amazon S3 location (bucket name and object key) where DataBrew can write output from a job.
   *
   * _Required_: Yes
   *
   * _Type_: [S3Location](aws-properties-databrew-job-s3location.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Location: DataBrewJobS3Location;
}

/**
 * The location in Amazon S3 or AWS Glue Data Catalog where the job writes its output.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-job-outputlocation.html}
 **/
export interface DataBrewJobOutputLocation {
  /**
   * The Amazon S3 bucket name.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Bucket: Value<string>;
  /**
   * Property description not available.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  BucketOwner?: Value<string>;
  /**
   * The unique name of the object in the bucket.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Key?: Value<string>;
}

/**
 * Represents a JDBC database output object which defines the output destination for a DataBrew recipe job to write into.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-job-databaseoutput.html}
 **/
export interface DataBrewJobDatabaseOutput {
  /**
   * The output mode to write into the database. Currently supported option: NEW_TABLE.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Allowed values_: `NEW_TABLE`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  DatabaseOutputMode?: Value<string>;
  /**
   * Represents options that specify how and where DataBrew writes the database output generated by recipe jobs.
   *
   * _Required_: Yes
   *
   * _Type_: [DatabaseTableOutputOptions](aws-properties-databrew-job-databasetableoutputoptions.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  DatabaseOptions: DataBrewJobDatabaseTableOutputOptions;
  /**
   * The AWS Glue connection that stores the connection information for the target database.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Minimum_: `1`
   *
   * _Maximum_: `255`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  GlueConnectionName: Value<string>;
}

/**
 * Represents options that specify how and where DataBrew writes the database output generated by recipe jobs.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-job-databasetableoutputoptions.html}
 **/
export interface DataBrewJobDatabaseTableOutputOptions {
  /**
   * Represents an Amazon S3 location (bucket name and object key) where DataBrew can store intermediate results.
   *
   * _Required_: No
   *
   * _Type_: [S3Location](aws-properties-databrew-job-s3location.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  TempDirectory?: DataBrewJobS3Location;
  /**
   * A prefix for the name of a table DataBrew will create in the database.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Minimum_: `1`
   *
   * _Maximum_: `255`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  TableName: Value<string>;
}

/**
 * Configuration for column evaluations for a profile job. ColumnStatisticsConfiguration can be used to select evaluations and override parameters of evaluations for particular columns.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-job-columnstatisticsconfiguration.html}
 **/
export interface DataBrewJobColumnStatisticsConfiguration {
  /**
   * Configuration for evaluations. Statistics can be used to select evaluations and override parameters of evaluations.
   *
   * _Required_: Yes
   *
   * _Type_: [StatisticsConfiguration](aws-properties-databrew-job-statisticsconfiguration.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Statistics: DataBrewJobStatisticsConfiguration;
  /**
   * List of column selectors. Selectors can be used to select columns from the dataset. When selectors are undefined, configuration will be applied to all supported columns.
   *
   * _Required_: No
   *
   * _Type_: List of [ColumnSelector](aws-properties-databrew-job-columnselector.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Selectors?: List<DataBrewJobColumnSelector>;
}

/**
 * Configuration for profile jobs. Configuration can be used to select columns, do evaluations, and override default parameters of evaluations. When configuration is undefined, the profile job will apply default settings to all supported columns.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-job-profileconfiguration.html}
 **/
export interface DataBrewJobProfileConfiguration {
  /**
   * List of column selectors. ProfileColumns can be used to select columns from the dataset. When ProfileColumns is undefined, the profile job will profile all supported columns.
   *
   * _Required_: No
   *
   * _Type_: List of [ColumnSelector](aws-properties-databrew-job-columnselector.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  ProfileColumns?: List<DataBrewJobColumnSelector>;
  /**
   * Configuration for inter-column evaluations. Configuration can be used to select evaluations and override parameters of evaluations. When configuration is undefined, the profile job will run all supported inter-column evaluations.
   *
   * _Required_: No
   *
   * _Type_: [StatisticsConfiguration](aws-properties-databrew-job-statisticsconfiguration.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  DatasetStatisticsConfiguration?: DataBrewJobStatisticsConfiguration;
  /**
   * List of configurations for column evaluations. ColumnStatisticsConfigurations are used to select evaluations and override parameters of evaluations for particular columns. When ColumnStatisticsConfigurations is undefined, the profile job will profile all supported columns and run all supported evaluations.
   *
   * _Required_: No
   *
   * _Type_: List of [ColumnStatisticsConfiguration](aws-properties-databrew-job-columnstatisticsconfiguration.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  ColumnStatisticsConfigurations?: List<DataBrewJobColumnStatisticsConfiguration>;
  /**
   * Configuration of entity detection for a profile job. When undefined, entity detection is disabled.
   *
   * _Required_: No
   *
   * _Type_: [EntityDetectorConfiguration](aws-properties-databrew-job-entitydetectorconfiguration.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  EntityDetectorConfiguration?: DataBrewJobEntityDetectorConfiguration;
}

/**
 * Configuration of entity detection for a profile job. When undefined, entity detection is disabled.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-job-entitydetectorconfiguration.html}
 **/
export interface DataBrewJobEntityDetectorConfiguration {
  /**
   * Entity types to detect. Can be any of the following:
   */
  EntityTypes: List<Value<string>>;
  /**
   * Configuration of statistics that are allowed to be run on columns that contain detected entities. When undefined, no statistics will be computed on columns that contain detected entities.
   *
   * _Required_: No
   *
   * _Type_: [AllowedStatistics](aws-properties-databrew-job-allowedstatistics.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  AllowedStatistics?: DataBrewJobAllowedStatistics;
}

/**
 * Represents a set of options that define how DataBrew will write a comma-separated value (CSV) file.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-job-csvoutputoptions.html}
 **/
export interface DataBrewJobCsvOutputOptions {
  /**
   * A single character that specifies the delimiter used to create CSV job output.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Minimum_: `1`
   *
   * _Maximum_: `1`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Delimiter?: Value<string>;
}

/**
 * Represents one or more actions to be performed on a DataBrew dataset.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-job-recipe.html}
 **/
export interface DataBrewJobRecipe {
  /**
   * The identifier for the version for the recipe.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Version?: Value<string>;
  /**
   * The unique name for the recipe.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Minimum_: `1`
   *
   * _Maximum_: `255`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Name: Value<string>;
}

/**
 * Represents options that specify how and where in Amazon S3 DataBrew writes the output generated by recipe jobs or profile jobs.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-job-output.html}
 **/
export interface DataBrewJobOutput {
  /**
   * A value that, if true, means that any data in the location specified for output is overwritten with new output.
   *
   * _Required_: No
   *
   * _Type_: Boolean
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Overwrite?: Value<boolean>;
  /**
   * The data format of the output of the job.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Allowed values_: `AVRO | CSV | GLUEPARQUET | JSON | ORC | PARQUET | TABLEAUHYPER | XML`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Format?: Value<string>;
  /**
   * The maximum number of files to be generated by the job and written to the output folder.
   *
   * _Required_: No
   *
   * _Type_: Integer
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  MaxOutputFiles?: Value<number>;
  /**
   * The compression algorithm used to compress the output text of the job.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Allowed values_: `BROTLI | BZIP2 | DEFLATE | GZIP | LZ4 | LZO | SNAPPY | ZLIB | ZSTD`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  CompressionFormat?: Value<string>;
  /**
   * The names of one or more partition columns for the output of the job.
   *
   * _Required_: No
   *
   * _Type_: List of String
   *
   * _Maximum_: `200`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  PartitionColumns?: List<Value<string>>;
  /**
   * Represents options that define how DataBrew formats job output files.
   *
   * _Required_: No
   *
   * _Type_: [OutputFormatOptions](aws-properties-databrew-job-outputformatoptions.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  FormatOptions?: DataBrewJobOutputFormatOptions;
  /**
   * The location in Amazon S3 where the job writes its output.
   *
   * _Required_: Yes
   *
   * _Type_: [S3Location](aws-properties-databrew-job-s3location.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Location: DataBrewJobS3Location;
}

/**
 * Selector of a column from a dataset for profile job configuration. One selector includes either a column name or a regular expression.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-job-columnselector.html}
 **/
export interface DataBrewJobColumnSelector {
  /**
   * A regular expression for selecting a column from a dataset.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Minimum_: `1`
   *
   * _Maximum_: `255`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Regex?: Value<string>;
  /**
   * The name of a column from a dataset.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Minimum_: `1`
   *
   * _Maximum_: `255`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Name?: Value<string>;
}

/**
 * Configuration of evaluations for a profile job. This configuration can be used to select evaluations and override the parameters of selected evaluations.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-job-statisticsconfiguration.html}
 **/
export interface DataBrewJobStatisticsConfiguration {
  /**
   * List of included evaluations. When the list is undefined, all supported evaluations will be included.
   *
   * _Required_: No
   *
   * _Type_: List of String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  IncludedStatistics?: List<Value<string>>;
  /**
   * List of overrides for evaluations.
   *
   * _Required_: No
   *
   * _Type_: List of [StatisticOverride](aws-properties-databrew-job-statisticoverride.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Overrides?: List<DataBrewJobStatisticOverride>;
}

/**
 * Configuration of statistics that are allowed to be run on columns that contain detected entities. When undefined, no statistics will be computed on columns that contain detected entities.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-job-allowedstatistics.html}
 **/
export interface DataBrewJobAllowedStatistics {
  /**
   * One or more column statistics to allow for columns that contain detected entities.
   *
   * _Required_: Yes
   *
   * _Type_: List of String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Statistics: List<Value<string>>;
}

/**
 * Override of a particular evaluation for a profile job.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-job-statisticoverride.html}
 **/
export interface DataBrewJobStatisticOverride {
  /**
   * A map that includes overrides of an evaluation’s parameters.
   *
   * _Required_: Yes
   *
   * _Type_: Map of String
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Parameters: { [key: string]: Value<string> };
  /**
   * The name of an evaluation
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Minimum_: `1`
   *
   * _Maximum_: `128`
   *
   * _Pattern_: `^[A-Z_]+$`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Statistic: Value<string>;
}

/**
 * A sample configuration for profile jobs only, which determines the number of rows on which the profile job is run. If a `JobSample` value isn't provided, the default is used. The default value is CUSTOM_ROWS for the mode parameter and 20,000 for the size parameter.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-job-jobsample.html}
 **/
export interface DataBrewJobJobSample {
  /**
   * The `Size` parameter is only required when the mode is CUSTOM_ROWS. The profile job is run on the specified number of rows. The maximum value for size is Long.MAX_VALUE.
   *
   * Long.MAX_VALUE = 9223372036854775807
   *
   * _Required_: No
   *
   * _Type_: Integer
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Size?: Value<number>;
  /**
   * A value that determines whether the profile job is run on the entire dataset or a specified number of rows. This value must be one of the following:
   */
  Mode?: Value<string>;
}
export interface DataBrewJobProperties {
  /**
   * The maximum number of times to retry the job after a job run fails.
   *
   * _Required_: No
   *
   * _Type_: Integer
   *
   * _Minimum_: `0`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  MaxRetries?: Value<number>;
  /**
   * The name of the project that the job is associated with.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Minimum_: `1`
   *
   * _Maximum_: `255`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  ProjectName?: Value<string>;
  /**
   * A series of data transformation steps that the job runs.
   *
   * _Required_: No
   *
   * _Type_: [Recipe](aws-properties-databrew-job-recipe.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Recipe?: DataBrewJobRecipe;
  /**
   * The Amazon Resource Name (ARN) of an encryption key that is used to protect the job output. For more information, see [Encrypting data written by DataBrew jobs](https://docs.aws.amazon.com/databrew/latest/dg/encryption-security-configuration.html)
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Minimum_: `20`
   *
   * _Maximum_: `2048`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  EncryptionKeyArn?: Value<string>;
  /**
   * The current status of Amazon CloudWatch logging for the job.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Allowed values_: `DISABLE | ENABLE`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  LogSubscription?: Value<string>;
  /**
   * The job's timeout in minutes. A job that attempts to run longer than this timeout period ends with a status of `TIMEOUT`.
   *
   * _Required_: No
   *
   * _Type_: Integer
   *
   * _Minimum_: `0`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Timeout?: Value<number>;
  /**
   * Represents a list of JDBC database output objects which defines the output destination for a DataBrew recipe job to write into.
   *
   * _Required_: No
   *
   * _Type_: List of [DatabaseOutput](aws-properties-databrew-job-databaseoutput.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  DatabaseOutputs?: List<DataBrewJobDatabaseOutput>;
  /**
   * Property description not available.
   *
   * _Required_: No
   *
   * _Type_: [OutputLocation](aws-properties-databrew-job-outputlocation.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  OutputLocation?: DataBrewJobOutputLocation;
  /**
   * The Amazon Resource Name (ARN) of the role to be assumed for this job.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Minimum_: `20`
   *
   * _Maximum_: `2048`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  RoleArn: Value<string>;
  /**
   * The unique name of the job.
   *
   * _Required_: Yes
   *
   * _Type_: String
   *
   * _Minimum_: `1`
   *
   * _Maximum_: `240`
   *
   * _Update requires_: [Replacement](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-replacement)
   */
  Name: Value<string>;
  /**
   * The job type of the job, which must be one of the following:
   */
  Type: Value<string>;
  /**
   * A dataset that the job is to process.
   *
   * _Required_: No
   *
   * _Type_: String
   *
   * _Minimum_: `1`
   *
   * _Maximum_: `255`
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  DatasetName?: Value<string>;
  /**
   * Configuration for profile jobs. Configuration can be used to select columns, do evaluations, and override default parameters of evaluations. When configuration is undefined, the profile job will apply default settings to all supported columns.
   *
   * _Required_: No
   *
   * _Type_: [ProfileConfiguration](aws-properties-databrew-job-profileconfiguration.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  ProfileConfiguration?: DataBrewJobProfileConfiguration;
  /**
   * One or more artifacts that represent output from running the job.
   *
   * _Required_: No
   *
   * _Type_: List of [Output](aws-properties-databrew-job-output.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  Outputs?: List<DataBrewJobOutput>;
  /**
   * List of validation configurations that are applied to the profile job.
   *
   * _Required_: No
   *
   * _Type_: List of [ValidationConfiguration](aws-properties-databrew-job-validationconfiguration.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  ValidationConfigurations?: List<DataBrewJobValidationConfiguration>;
  /**
   * Metadata tags that have been applied to the job.
   *
   * _Required_: No
   *
   * _Type_: List of [Tag](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html)
   *
   * _Update requires_: [Replacement](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-replacement)
   */
  Tags?: List<ResourceTag>;
  /**
   * A sample configuration for profile jobs only, which determines the number of rows on which the profile job is run. If a `JobSample` value isn't provided, the default value is used. The default value is CUSTOM_ROWS for the mode parameter and 20,000 for the size parameter.
   *
   * _Required_: No
   *
   * _Type_: [JobSample](aws-properties-databrew-job-jobsample.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  JobSample?: DataBrewJobJobSample;
  /**
   * The encryption mode for the job, which can be one of the following:
   */
  EncryptionMode?: Value<string>;
  /**
   * The maximum number of nodes that can be consumed when the job processes data.
   *
   * _Required_: No
   *
   * _Type_: Integer
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  MaxCapacity?: Value<number>;
  /**
   * One or more artifacts that represent the AWS Glue Data Catalog output from running the job.
   *
   * _Required_: No
   *
   * _Type_: List of [DataCatalogOutput](aws-properties-databrew-job-datacatalogoutput.md)
   *
   * _Update requires_: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
   */
  DataCatalogOutputs?: List<DataBrewJobDataCatalogOutput>;
}

/**
 * Specifies a new DataBrew job.
 * {@link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-databrew-job.html}
 */
export interface DataBrewJobResource {
  Type: 'AWS::DataBrew::Job';
  Properties: DataBrewJobProperties;
}
